services:
  # PostgreSQL Database Service
  db:
    image: postgres:17-alpine
    container_name: stateful-container
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: stateful-db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U root -d schuco_db" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
